---
apiVersion: v1
kind: Service
metadata:
  name: app-front-svc
  namespace: ${NAMESPACE}
  labels:
    app: app-front
spec:
  selector:
    app: app-front
  ports:
    - port: 3000
      targetPort: 3000
