name: "Deploy On Amazon EKS"
description: "Deploy Docker Image on Amazon EKS"
inputs:
   role-to-assume:
     required: true
     description: "AWS Credential"
   aws-region:
     required: true
     description: "AWS Region"
     default: "us-east-1"
   ks8-context:
     required: true
     description: "KS8 context name given by EKS"
     default: "Production"
   image-tag:
     required: true
     description: "Image tag to use"
   site-url:
     required: true
     description: "Domain name of the site"
   namespace:
     required: true
     description: "Namespace in k8s"
runs:
  using: "composite"
  steps:
    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.24.3'
      id: install

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        aws-region: ${{ inputs.aws-region }}

    - name: Update kube config
      shell: bash
      run: aws eks update-kubeconfig --name ${{ inputs.ks8-context }} --region ${{ inputs.aws-region }}

    - name: Deploy image to Amazon EKS
      shell: bash
      run: |
          cat docker/k8s/${{ inputs.namespace }}/01-deployments.yaml | sed -e "s#\${IMAGE_TAG}#${{ inputs.image-tag }}#g" -e "s#\${NAMESPACE}#${{ inputs.namespace }}#g" | kubectl apply -f -
          cat docker/k8s/${{ inputs.namespace }}/02-services.yaml | sed -e "s#\${NAMESPACE}#${{ inputs.namespace }}#g" | kubectl apply -f -
          cat docker/k8s/${{ inputs.namespace }}/03-ingress.yaml | sed -e "s#\${SITE_URL}#${{ inputs.site-url }}#g" -e "s#\${NAMESPACE}#${{ inputs.namespace }}#g" | kubectl apply -f -
