name: "Build and Deploy Docker Image"
description: "Build and Deploy Docker Image on Github Container Registry"
inputs:
   repository-owner:
     required: true
     description: "Repository Owner"
   github-token:
     required: true
     description: "Github Token"
   dockerfile-path:
     required: true
     description: "Path where Dockerfile is located"
     default: "./docker/Dockerfile"
   image-tag:
     required: true
     description: "Image tag to use"
runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ inputs.repository-owner }}
        password: ${{ inputs.github-token }}

    - name: Build and push
      id: build_image
      uses: docker/build-push-action@v3
      with:
        file: ${{ inputs.dockerfile-path }}
        push: true
        tags: |
          ${{ inputs.image-tag }}
